config/routes.rb
Rails.application.routes.draw do
	root		'home#index'
	get			'/login',	to: 'sessions#new'
	post		'/login',	to: 'sessions#create'
	delete		'/logout',	to: 'sessions#destroy'
	get			'/tables',	to: 'home#tables'
	resources	:subscribes
	resources	:contacts
	resources	:home
	#get			'*path',	to: redirect('/')
end

app/models/admin.rb
class Admin < ApplicationRecord
	before_save {self.user = user.downcase}
	validates :user, presence: true, length: {maximum: 50}
	validates :password, presence: true, length: {maximum: 50}
	has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	before_save {self.email = email.downcase}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {minimum: 1, maximum: 255}, format: {with: VALID_EMAIL_REGEX}
	validates :subject, presence: true, length: {minimum: 1, maximum: 255}
	validates :message, presence: true, length: {minimum: 1, maximum: 800}
end

app/models/subscribe.rb
class Subscribe < ApplicationRecord
	before_save {self.email = email.downcase}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: {maximum: 255}, format: {with: VALID_EMAIL_REGEX}, uniqueness: {case_sensitive: false}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	def create
		@contact = Contact.new(contact_params)
		
		if @contact.save
			redirect_to root_path, notice: '<p>The message was successfully sent.</p>'
		end
	end

	private
		def contact_params
			params.require(:contact).permit(:email, :subject, :message)
		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		#@admin = Admin.new(user: 'fulllab', password: 'rails')
		#@admin.save
	end

	def admin
	end

	def tables
		@subscribes = Subscribe.all.order('id ASC')
		@contacts = Contact.all.order('id ASC')
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    admin = Admin.find_by(user: params[:session][:user].downcase)
  	
  	if admin && admin.authenticate(params[:session][:password])
      log_in admin
      redirect_to tables_path, notice: '<p>You are now logged in.</p>'
  	else
      flash[:danger] = '<p>Invalid admin credentials.</p>'
  		render 'new'
  	end
  end

  def destroy
    log_out
    redirect_to root_path, notice: '<p>You are now logged out.</p>'
  end
end

app/controllers/subscribes_controller.rb
class SubscribesController < ApplicationController
	def create
		@subscribe = Subscribe.new(subscribe_params)
		
		if @subscribe.save
			redirect_to root_path, notice: '<p>Successfully subscribed.</p>'
		end
	end

	private
		def subscribe_params
			params.require(:subscribe).permit(:email)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def log_out
		session[:user_id] = nil
	end

	def current_user
		@current_user ||= Admin.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end
end

app/helpers/subscribe_helper.rb
module SubscribeHelper
end

app/views/home/index.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<a class="navbar-brand" href="#" alt="Piano">
				<%= image_tag('navbar/logo.png', alt: 'Piano') %>
			</a>
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
				<i class="fa fa-bars" aria-hidden="true"></i>
			</button>
		</div>
		<div id="navbar" class="collapse navbar-collapse navbar-right">
			<ul class="nav navbar-nav">
				<li>
					<a href="#jumbotron">Top</a>
				</li>
				<li>
					<a href="#project">The project</a>
				</li>
				<li>
					<a href="#clients">Clients</a>
				</li>
				<li>
					<a href="#about">About</a>
				</li>
				<li>
					<a href="#contact">Contact</a>
				</li>
			</ul>
		</div>
	</div>
</nav>
<div id="jumbotron" class="jumbotron">
	<div class="container">
		<h2>We're coming soon</h2>
		<p>We are working very hard on our new site. Sign up to our newsletter and you'll be one of the first to know when it's ready:</p>
		<%= form_for :subscribe, url: subscribes_path do |f| %>
			<%= f.email_field :email, placeholder: 'Enter your email...' %>
			<%= f.submit 'Subscribe', class: 'btn btn-default' %>
		<% end %>
		<i class="button fa fa-chevron-down go-to-time"></i>
	</div>
</div>
<section id="time">
	<div class="container">
		<div class="row">
			<div class="col-xs-8 text-center">
				<h3>Ok, but how long does it take?</h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
				<div class="divider"></div>
				<p><span class="number">24</span><span class="letter">d</span><span class="slash">/</span><span class="number">23</span><span class="letter">h</span><span class="slash">/</span><span class="number">58</span><span class="letter">m</span><span class="slash">/</span><span class="number">20</span><span class="letter">s</p>
			</div>
			<div class="col-xs-3 offset-xs-1">
				<%= image_tag('time/clock.png') %>
			</div>
		</div>
	</div>
</section>
<section id="project" class="text-center">
	<h2>The project</h2>
	<div class="divider"></div>
	<div class="description container">
		<p>Claritas est etiam processus dynamicus, qui sequitur mutationem consuetudium lectorum. Mirum est notare quam littera gothica, quam nunc putamus parum claram lorem.</p>
	</div>
	<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<div class="icon">
				<i class="fa fa-cogs"></i>
			</div>
			<h3>New Features</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
		</div>
		<div class="col-xs-3">
			<div class="icon">
				<i class="fa fa-mobile"></i>
			</div>
			<h3>Responsive</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
		</div>
		<div class="col-xs-3">
			<div class="icon">
				<i class="fa fa-pencil"></i>
			</div>
			<h3>Flat Design</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
		</div>
		<div class="col-xs-3">
			<div class="icon">
				<i class="fa fa-twitter"></i>
			</div>
			<h3>Social</h3>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</p>
		</div>
	</div>
	</div>
</section>
<section id="quote" class="text-center">
	<div class="container">
		<p>"Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful."</p>
		<p>ALBERT SCHWEITZER</p>
	</div>
</section>
<section id="clients">
	<div class="container">
		<div class="row">
			<div class="col-xs-4">
				<%= image_tag('time/speech_bubbles.png') %>
			</div>
			<div class="col-xs-8 text-center">
				<h3>What our clients say</h3>
				<p>Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl.</p>
				<h4>John Doe, johndoe.com</h4>
				<div class="row">
					<%= image_tag('clients/1.jpg', class: 'col-xs-3') %>
					<%= image_tag('clients/2.jpg', class: 'col-xs-3') %>
					<%= image_tag('clients/3.jpg', class: 'col-xs-3') %>
					<%= image_tag('clients/4.jpg', class: 'col-xs-3') %>
				</div>
			</div>
		</div>
	</div>
</section>
<section id="experience">
	<div class="container">
		<div class="row text-center">
			<div class="col-xs-3">
				<h3>We have the experience:</h3>
			</div>
			<div class="col-xs-3">
				<h4>3</h4>
				<p>Years of experience</p>
			</div>
			<div class="col-xs-3">
				<h4>70</h4>
				<p>Projects completed</p>
			</div>
			<div class="col-xs-3">
				<h4>3236</h4>
				<p>Lines of code</p>
			</div>
		</div>
	</div>
</section>
<section id="about" class="text-center">
	<h2>About us</h2>
	<div class="divider"></div>
	<div class="container">
		<p>Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Ut wisi enim ad minim veniam, quis nostrud.</p>
	</div>
	<div class="row">
		<div class="col-xs-6">
			<div class="row">
				<%= image_tag('about/1.jpg', class: 'col-xs-3 pull-right') %>
				<div class="col-xs-8 pull-right">
					<h3>Jane Doe</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.</p>
					<div class="social">
						<i class="fa fa-facebook"></i>
						<i class="fa fa-dribbble"></i>
						<i class="fa fa-twitter"></i>
						<i class="fa fa-pinterest"></i>
					</div>
				</div>
			</div>
			<div class="row">
				<%= image_tag('about/3.jpg', class: 'col-xs-3 pull-right') %>
				<div class="col-xs-8 pull-right">
					<h3>Sarah Red</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.</p>
					<div class="social">
						<i class="fa fa-facebook"></i>
						<i class="fa fa-dribbble"></i>
						<i class="fa fa-twitter"></i>
						<i class="fa fa-pinterest"></i>
					</div>
				</div>
			</div>
		</div>
		<div class="col-xs-6">
			<div class="row">
				<%= image_tag('about/2.jpg', class: 'col-xs-3') %>
				<div class="col-xs-8">
					<h3>Tim Brown</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.</p>
					<div class="social left">
						<i class="fa fa-facebook"></i>
						<i class="fa fa-dribbble"></i>
						<i class="fa fa-twitter"></i>
						<i class="fa fa-pinterest"></i>
					</div>
				</div>
			</div>
			<div class="row">
				<%= image_tag('about/4.jpg', class: 'col-xs-3') %>
				<div class="col-xs-8">
					<h3>James White</h3>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod.</p>
					<div class="social left">
						<i class="fa fa-facebook"></i>
						<i class="fa fa-dribbble"></i>
						<i class="fa fa-twitter"></i>
						<i class="fa fa-pinterest"></i>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<section id="contact-msg">
	<div class="container text-center">
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p>
		<button type="button" class="btn btn-default go-to-contact">Contact us now!</button>
	</div>
</section>
<section id="contact" class="text-center">
	<h2>Contact us</h2>
	<div class="divider"></div>
	<div class="description container">
		<p>For every question, information or just to say "Hi", here you can get in touch with us. Just fill in the form below and we'll reply as soon as possible.</p>
	</div>
	<%= form_for :contact, url: contacts_path do |f| %>
		<div class="container">
			<%= f.email_field :email, placeholder: 'Email...' %>
			<%= f.text_field :subject, placeholder: 'Subject...' %>
			<%= f.text_area :message, placeholder: 'Message...' %>
			<%= f.submit 'Send it', class: 'btn btn-default' %>
		</div>
	<% end %>
	
	<i class="button fa fa-chevron-up go-to-start"></i>
</section>
<footer>
	<div class="container">
		<p>&copy; Piano Bootstrap Template by Azmind.</p>
		<div class="social">
			<i class="fa fa-facebook"></i>
			<i class="fa fa-dribbble"></i>
			<i class="fa fa-twitter"></i>
			<i class="fa fa-google-plus"></i>
			<i class="fa fa-pinterest"></i>
		</div>
	</div>
</footer>
<aside id="admin_box" class="closed">
	<div class="content">
		<div class="button">
			<i class="fa fa-chevron-up"></i>
		</div>
		<%= button_to 'Admin Panel', login_path, method: :get, class: 'btn btn-default' %>
	</div>
</aside>
<% if flash[:notice] %>
	<script>
		bootstrapAlert('<%= flash[:notice].html_safe %>', 'alert-success');
	</script>
<% end %>

app/views/home/tables.html.erb
<% if logged_in? %>
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="#" alt="Piano">
					<%= image_tag('navbar/logo.png', alt: 'Piano') %>
				</a>
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
					<i class="fa fa-bars" aria-hidden="true"></i>
				</button>
			</div>
			<div id="navbar" class="collapse navbar-collapse navbar-right">
				<ul class="nav navbar-nav">
					<li>
						<%= link_to 'Back to main page', root_path, method: :get %>
					</li>
					<li>
						<%= link_to 'Log out', logout_path, method: :delete %>
					</li>
				</ul>
			</div>
		</div>
	</nav>
	<div id="jumbotron">
		<div class="container">
			<h2>Admin Panel</h2>
			<p class="reverse">Subscribes</p>
			<table class="table table-bordered table-responsive">
				<tr>
					<th>#</th>
					<th>email</th>
				</tr>
				<% @subscribes.each_with_index do |s, i| %>
					<tr>
						<td scope="row"><%= i + 1 %></td>
						<td><%= s.email %></td>
					</tr>
				<% end %>
			</table>
			<p class="reverse">Contacts</p>
			<table class="table table-bordered table-responsive">
				<tr>
					<th>#</th>
					<th>email</th>
					<th>subject</th>
					<th>message</th>
				</tr>
				<% @contacts.each_with_index do |c, i| %>
					<tr>
						<td><%= i + 1 %></td>
						<td><%= c.email %></td>
						<td><%= c.subject %></td>
						<td><%= c.message %></td>
					</tr>
				<% end %>
			</table>
		</div>
	</div>
	<% if flash[:notice] %>
		<script>
			bootstrapAlert('<%= flash[:notice].html_safe %>', 'alert-success');
		</script>
	<% end %>
<% else %>
	<% controller.redirect_to root_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en_us">
  <head>
    <title>Prova Fulllab</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', 'https://fonts.googleapis.com/css?family=Open+Sans:300,700' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'https://use.fontawesome.com/944949779d.js' %>
  </head>
  <body data-spy="scroll" data-target=".navbar" data-offset="66">
    <%= yield %>
  </body>
</html>